name: Deploy PROD app

on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Deploy Live app
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
        dokku-host: ${{ secrets.IP_ADDRESS }}
        app-name: live
